//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 12:28:49 AM CST 
//


package scores.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the scores.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScoresRequest_QNAME = new QName("http://www.wgluka.com.cn/2048/", "ScoresRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: scores.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScoresResponse }
     * 
     */
    public ScoresResponse createScoresResponse() {
        return new ScoresResponse();
    }

    /**
     * Create an instance of {@link ScoreResponse }
     * 
     */
    public ScoreResponse createScoreResponse() {
        return new ScoreResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wgluka.com.cn/2048/", name = "ScoresRequest")
    public JAXBElement<Object> createScoresRequest(Object value) {
        return new JAXBElement<Object>(_ScoresRequest_QNAME, Object.class, null, value);
    }

}
