//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 12:28:49 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wgluka.com.cn/2048/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package scores.wsdl;
